version: '3.8'
services:
  api2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: course-recommender-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    restart: unless-stopped
